mkdir -p /scratch/zgh23/sparse_mat
pushd .
cd /scratch/zgh23/sparse_mat
wget https://sparse.tamu.edu/MM/HB/bcsstk12.tar.gz
wget https://sparse.tamu.edu/MM/HB/bp_1400.tar.gz
wget https://sparse.tamu.edu/MM/HB/fs_760_3.tar.gz
wget https://sparse.tamu.edu/MM/HB/gre_512.tar.gz
wget https://sparse.tamu.edu/MM/HB/west0497.tar.gz
wget https://sparse.tamu.edu/MM/Bai/odepb400.tar.gz
wget https://sparse.tamu.edu/MM/Bai/pde900.tar.gz
wget https://sparse.tamu.edu/MM/Boeing/bcsstm38.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex12.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex2.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex20.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex21.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex22.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex23.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex24.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex25.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex26.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex27.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex28.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex29.tar.gz
wget https://sparse.tamu.edu/MM/Grund/bayer10.tar.gz
wget https://sparse.tamu.edu/MM/Gset/G29.tar.gz
wget https://sparse.tamu.edu/MM/Hollinger/jan99jac100sc.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lp_scfxm1.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lp_standmps.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lp_woodw.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lpi_cplex2.tar.gz
wget https://sparse.tamu.edu/MM/Mallya/lhr71.tar.gz
wget https://sparse.tamu.edu/MM/Mallya/lhr71c.tar.gz
wget https://sparse.tamu.edu/MM/Nemeth/nemeth16.tar.gz
wget https://sparse.tamu.edu/MM/vanHeukelum/cage12.tar.gz
wget https://sparse.tamu.edu/MM/Andrews/Andrews.tar.gz
wget https://sparse.tamu.edu/MM/Sandia/adder_dcop_21.tar.gz
wget https://sparse.tamu.edu/MM/Sandia/adder_dcop_37.tar.gz
wget https://sparse.tamu.edu/MM/Sandia/fpga_dcop_36.tar.gz
wget https://sparse.tamu.edu/MM/Sandia/oscil_dcop_30.tar.gz
wget https://sparse.tamu.edu/MM/Sandia/oscil_dcop_39.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/t2dal_e.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/t3dh_a.tar.gz
wget https://sparse.tamu.edu/MM/Cannizzo/sts4098.tar.gz
wget https://sparse.tamu.edu/MM/GHS_indef/c-55.tar.gz
wget https://sparse.tamu.edu/MM/GHS_indef/sit100.tar.gz
wget https://sparse.tamu.edu/MM/GHS_psdef/oilpan.tar.gz
wget https://sparse.tamu.edu/MM/DNVS/x104.tar.gz
wget https://sparse.tamu.edu/MM/PARSEC/GaAsH6.tar.gz
wget https://sparse.tamu.edu/MM/AMD/G3_circuit.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/flowmeter5.tar.gz
wget https://sparse.tamu.edu/MM/Schenk_IBMNA/c-36.tar.gz
wget https://sparse.tamu.edu/MM/Schenk_IBMNA/c-42.tar.gz
wget https://sparse.tamu.edu/MM/Schenk_IBMNA/c-44.tar.gz
wget https://sparse.tamu.edu/MM/Mittelmann/rail2586.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/gams10am.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/seymourl.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/stat96v3.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/tp-6.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/scagr7-2r.tar.gz
wget https://sparse.tamu.edu/MM/YCheng/psse0.tar.gz
wget https://sparse.tamu.edu/MM/CEMW/t2em.tar.gz
wget https://sparse.tamu.edu/MM/TKK/cyl6.tar.gz
wget https://sparse.tamu.edu/MM/JGD_CAG/CAG_mat1916.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch5-5-b4.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch7-6-b3.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch7-6-b4.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b13.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b14.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b13.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b14.tar.gz
wget https://sparse.tamu.edu/MM/TSOPF/TSOPF_FS_b300_c1.tar.gz
wget https://sparse.tamu.edu/MM/Rommes/M80PI_n1.tar.gz
wget https://sparse.tamu.edu/MM/Rommes/M80PI_n.tar.gz
wget https://sparse.tamu.edu/MM/DIMACS10/vsp_data_and_seymourl.tar.gz
wget https://sparse.tamu.edu/MM/DIMACS10/vsp_p0291_seymourl_iiasa.tar.gz
wget https://sparse.tamu.edu/MM/DIMACS10/vsp_sctap1-2b_and_seymourl.tar.gz
wget https://sparse.tamu.edu/MM/VDOL/freeFlyingRobot_3.tar.gz
wget https://sparse.tamu.edu/MM/VLSI/mosfet2.tar.gz
wget https://sparse.tamu.edu/MM/Martin/marine1.tar.gz
popd
